### PR TITLE
Implements purging by keys in a batch

### PR DESCRIPTION
**Pull request by stanimoto**

### CODE REVIEW

**Comment by stanimoto** [comment]
Hello!

Any chances that this can get merged or could I get some feedback?

Thanks!

**Comment by annawinkler** [comment]
Hi @stanimoto ! Thank you for your PR! I will take a look 👀 and let you know.

**Comment by annawinkler** [comment]
It sounds like we will want to add a doc PR to update the docs here https://docs.fastly.com/api/purge#purge_db35b293f8a724717fcf25628d713583 @psbanka

**Comment by stanimoto** [comment]
> It sounds like we will want to add a doc PR to update the docs here https://docs.fastly.com/api/purge#purge_db35b293f8a724717fcf25628d713583 @psbanka

Hi @annawinkler and @psbanka ! The docs seem good to me, but please let me know if I can do anything!

**Comment by iffius** [comment]
@annawinkler @psbanka This PR seems to be languishing. It's a useful and provides parity with the API documentation (listed previously).  Is there anything we can do to get this PR to a place where it can be merged?

**Comment by annawinkler** [comment]
@iffius Apologies for the delay and we appreciate your patience. I'll see what we can do in the next week.

**Comment by psbanka** [comment]
Hey, @iffius — I have thoroughly tested these changes, and they look great. Will merge your PR. Sorry for the delay!

**Comment by stanimoto** [comment]
Thank you @annawinkler @psbanka for reviewing and @iffius for urging. :)

**Pull request merged**
