### PR TITLE
Generic way to get collection lists, plus general expansion of API support.

### PR DESCRIPTION
**Pull request by dcmoore-gd**
This incorporates changes from:

@djworth's PR #22 (with conflicts resolved)
@lisac's PR #29

Plus some, and adds in some additional methods.

### CODE REVIEW

**Comment by lisac** [comment]
this looks really cool, @dcmoore-gd ! And thanks for incorporating my PR, too. :) 
@thommahoney - would you have time to review this? I noticed the last commits on `master` are yours... or could you recommend someone who could do the review? thanks.

**Comment by dcmoore-gd** [comment]
And thank you @lisac for writing the `list` method!

**Comment by dcmoore-gd** [comment]
Whoa!  @psbanka is Fastly supporting this again?  Last we talked to them it was officially abandoned.  I'm hoping that's changed!

**Comment by davy** [comment]
We have always strived to incorporate useful contributions within a timely manner, but sometimes we've been better at this goal than others. We are glad @psbanka is now helping us improve in this area by keeping a closer eye on fastly-py! 🎉

**Comment by dcmoore-gd** [comment]
BTW @davy I didn't mean to imply anything negative!  I'd asked our Fastly rep and they'd said it wouldn't be supported anymore.  We're just happy that's changed!  Thanks!

**Pull request merged**
