### PR TITLE
update documentation for releasing

### PR DESCRIPTION
**Pull request by thommahoney**
The two commits on this branch will help us avoid https://github.com/fastly/fastly-py/issues/19 in the future.

### CODE REVIEW

**Comment by drbrain** [comment]
Isn't distributing a package something only we do?  Since this repo is public maybe this should be in a different file?

**Comment by blithe** [comment]
:+

**Comment by thommahoney** [comment]
> Isn't distributing a package something only we do? Since this repo is public maybe this should be in a different file?

I wasn't sure where else to put it. It doesn't expose anything secret so I went with README.md.

**Comment by drbrain** [comment]
OK.

My name is Eric Hodel and I approve this pull request.

**Pull request merged**
